"""Curated exact published results; re-run to export without estimating chart traces."""
from pathlib import Path
import hashlib,json
OUT=Path(__file__).resolve().parents[1]
URL='https://pmc.ncbi.nlm.nih.gov/articles/PMC8210748/'
claims=[]
def fact(id,claim,kind,location,measurements,limitations):
 claims.append(dict(id=id,claim=claim,evidenceType=kind,sourceUrl=URL,location=location,measurements=measurements,limitations=limitations,candidateIds=['HHAT:L75','HHAT:L75F']))
def value(state,endpoint,x,unit,error=None,errorType=None,n=None,censor='none',reason=None):
 return dict(state=state,endpoint=endpoint,value=x,unit=unit,uncertainty=error,uncertaintyType=errorType,n=n,censoring=censor,missingReason=reason)
fact('HHAT-E1','302TIL binds mutant pMHC more tightly in equilibrium SPR.','published_experiment','Table 1; Figure 2b; Online Methods: Surface plasmon resonance',[
 value('mutant','SPR equilibrium KD',9,'micromolar',1,'SD',9),value('normal','SPR equilibrium KD',200,'micromolar',30,'SD',9)],['25 C; Biacore T200; immobilized TCR; 1:1 steady-state fit; 10 mM HEPES pH 7.4, 150 mM NaCl, 3 mM EDTA, 0.005% P-20; 5-10 microliter/min; 600-2000 RU. This is receptor binding, not peptide-HLA affinity.'])
fact('HHAT-E2','The two peptide-HLA complexes have similar measured thermal melting temperatures.','published_experiment','Figure 1a printed inset; Online Methods: Thermal stability',[
 value('normal','melting temperature',54.7,'degree_C',.4,'SD',6),value('mutant','melting temperature',56.1,'degree_C',.2,'SD',6)],['Prometheus NanoDSF backscatter; approximately 10 micromolar protein; 1 C/min; HEPES/NaCl/EDTA/P-20 buffer as E1; derivative scattering fits. Thermal stability is a proxy used by authors; no direct peptide-HLA KD or IC50 measured here. Printed labels, not trace digitization.'])
fact('HHAT-E3','At 10 C mutant pMHC dissociates more slowly and has a faster derived association rate.','published_experiment','Figure 2c printed labels and caption; Online Methods: SPR',[
 value('mutant','SPR koff',1.35,'s^-1',reason='Uncertainty not printed for koff'),value('normal','SPR koff',4.87,'s^-1',reason='Uncertainty not printed for koff'),value('mutant','derived kon = koff/KD',170000,'M^-1 s^-1',50000,'propagated independent KD and koff error'),value('normal','derived kon = koff/KD',20000,'M^-1 s^-1',7000,'propagated independent KD and koff error')],['10 C; 50 microliter/min; approximately 500 RU; 10 Hz; single-exponential global dissociation fit of three injections. kon is calculated using independent 10 C KD, not directly fitted association. Do not combine with 25 C KD. Replicate uncertainty type for propagated inputs not fully specified in caption.'])
fact('HHAT-E4','Functional IL-2 response requires a lower peptide concentration for mutant in this cell assay.','published_experiment','Figure 2a printed labels and caption; Online Methods: T cell functional assays',[
 value('mutant','IL-2 response EC50',1.1,'micromolar',.1,'fit error'),value('normal','IL-2 response EC50',200,'micromolar',censor='lower_bound')],['CD8+ Jurkat76 expressing 302TIL and HLA-A*02:06 T2 cells; 2 h peptide pulse, 1:1 co-culture 18-20 h at 37 C; ELISA; two independent experiments with three biological replicates each. WT EC50 >=200, not exact. Not a binding assay.'])
fact('HHAT-E5','ITC independently detects mutant receptor binding; normal ITC binding was not measurable.','published_experiment','Extended Data Figure 2 caption; Online Methods: ITC; Results',[
 value('mutant','ITC KD replicate 1',1.7,'micromolar'),value('mutant','ITC KD replicate 2',1.4,'micromolar'),value('normal','ITC KD',None,'micromolar',censor='not_measurable',reason='Authors unable to measure; no numeric detection limit')],['25 C; MicroCal ITC200; 20 micromolar TCR, 170-190 micromolar pMHC; 10 mM HEPES pH7.4/150 mM NaCl; single-site fit. Prose says ITC KD higher than SPR, but caption values are lower. Preserve discrepancy; do not average assays.'])
fact('HHAT-G1','HLA-aligned structures quantify the change at W6 separately from the position-8 mutation.','computed_geometry','Deposited PDBs 6UJQ,6UJO,6UK2,6UK4; rosalind/mechanism.json w6Comparisons',[],['Fixed atom correspondence can give a large RMSD for indole ring flips; use torsions and endpoints alongside RMSD. No trajectory or conformational population measured.'])
fact('HHAT-G2','Recovered crystal mates place W6 next to Tyr100 alpha.','computed_geometry','rosalind/mechanism.json states[].w6Tyr100Alpha; Figure 3a context',[],['NE1-to-Tyr-ring centroid is not ring-to-ring centroid or minimum heavy-atom distance. Geometric proximity alone is not hydrogen-bond energy.'])
fact('HHAT-I1','The paper interprets altered W6 geometry and receptor kinetics as pre-organization for 302TIL recognition.','interpretation','Figures 1-3; Discussion',[],['Four static crystals establish conformations, not dynamic populations, transition rates, or mutation causality alone. Published dynamics are author analyses, not reproduced here. Ovarian HHAT case does not explain pancreatic vaccine outcomes.'])
fact('HHAT-E6','W6 chemical substitutions weaken or abolish detectable 302TIL binding in separate SPR ligand experiments.','published_experiment','Table 1; Extended Data Figure 5; verified against plugin-resolved PMC version 1 XML',[
 value('W6 Bta analogue, mutant F8 background','SPR equilibrium KD',170,'micromolar',30,'SD',3),value('W6 Bta analogue, normal L8 background','SPR equilibrium KD',1600,'micromolar',500,'SD',3),value('W6 alanine, mutant F8 background','SPR equilibrium KD',None,'micromolar',censor='not_measurable',reason='No binding detected; no numeric detection limit reported'),value('W6 alanine, normal L8 background','SPR equilibrium KD',None,'micromolar',censor='not_measurable',reason='No binding detected; no numeric detection limit reported'),value('position 8 alanine','SPR equilibrium KD',700,'micromolar',200,'SD',3)],['25 C SPR as in E1. Bta is 3-benzothienyl-l-alanine: an experimental Trp analogue, not a canonical sequence B. These ligands are not any of the four exported crystal structures. Perturbations support W6 involvement but do not isolate an exact hydrogen-bond energy or establish a vaccine response probability.'])
out={'schemaVersion':'0.1.0','study':'Devlin et al. 2020 ovarian HHAT structural case','claims':claims,'defaultNumericClaimIds':['HHAT-E1','HHAT-E2','HHAT-E3','HHAT-E4'],'provenance':{'operation':'Local public full-text retrieval and visual transcription of printed Figure 1/2 labels','workbench':False,'date':'2026-09-09'},'unsupported':[{'task':'Direct measured peptide-HLA equilibrium affinity','reason':'This paper reports thermal stability; no direct KD extracted.'}]}
(OUT/'evidence.json').write_text(json.dumps(out,indent=2)+'\n')
