"""Index unedited native PNGs and current capture gaps; never creates UI images."""
from pathlib import Path
import json,hashlib,struct,re
O=Path(__file__).resolve().parent;R=O.parents[1]
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
versions={}
for name,version in [('rosalind','0.2.5-research-preview'),('structure-viewer','0.1.80'),('sequence-viewer','0.1.43'),('life-sciences-literature','0.1.5')]:
 p=Path('/Users/alexandrakim/.codex/plugins/cache/openai-curated-remote')/name/version/'.codex-plugin/plugin.json'
 if p.exists():
  j=json.loads(p.read_text());versions[name]={'displayName':j.get('interface',{}).get('displayName',name),'version':j['version'],'manifestSha256':sha(p),'verification':'Read installed cache manifest this session; not proof of a mounted parent Workbench UI.'}
sources={k:{'path':p,'sha256':sha(R/p)} for k,p in {'primary':'public/structures/6UJQ.pdb','HHAT_mutant_free_6UJO':'public/structures/6UJO.pdb','HHAT_bound_mutant_6UK4':'rosalind/structures/6UK4.pdb','KRAS_normal_7OW5':'rosalind/contrast-kras/sources/7OW5.pdb','KRAS_mutant_7OW6':'rosalind/contrast-kras/sources/7OW6.pdb','deposited_6UJQ':'data/raw/6UJQ.pdb'}.items()}
descriptions={'01-hhat-native.png':('Do not use: overlapping native labels; retained original attempt.','rejected for label legibility'), '01-hhat-native-2.png':('Normal 6UJQ and mutant 6UJO unbound peptides in the existing locally prepared app HLA frame; native labels mark mutant TRP6/PHE8.','inspected; use this HHAT close-up'),'01b-hhat-receptor-native.png':('Prepared reconstructed mutant 6UK4 complex; HLA A:1–180, peptide C and 302TIL D/E:1–110 displayed. Crystal-mate reconstruction remains the earlier local preparation.','inspected; use as receptor context'),'02-kras-contacts-native.png':('7OW5/7OW6 bound JDIa41b1 peptides; both measured pairs belong to mutant 7OW6, C6 N–A70 OE1 and C6 OD2–A114 NH2. Closest-heavy-atom distances, not binding energies.','inspected; measurements readable at original size')}
images=[]
for p in sorted(O.glob('*.png')):
 data=p.read_bytes();assert data[:8]==b'\x89PNG\r\n\x1a\n';width,height=struct.unpack('>II',data[16:24]);side=p.with_name(p.name+'.render.json');original=side.read_bytes();j=json.loads(original)
 assert sha(p)==j['artifact']['sha256']
 if 'publicationRedactions' not in j:
  raw=original.decode();redacted=re.sub(r'viewer-file://[^\s"\\]+','[opaque-viewer-resource-redacted]',raw);j=json.loads(redacted);j['publicationRedactions']={'originalSidecarSha256':hashlib.sha256(original).hexdigest(),'reason':'Opaque local viewer resource URLs removed; source mapping/hashes in index.json. PNG bytes unchanged.'};side.write_text(json.dumps(j,indent=2)+'\n')
 description,qa=descriptions[p.name]
 images.append({'file':p.name,'width':width,'height':height,'sha256':sha(p),'capturedAt':j['createdAt'],'captureType':'native component render','plugin':'Molecular Structure Viewer','pluginVersion':versions.get('structure-viewer',{}).get('version'),'operation':'structure.render_image','operationId':j['provenance'].get('jobId'),'receipt':side.name,'sourceMappings':'index.json#sources','freshOperation':'Fresh native rendering of restored scientific scenes; not repeated research or a UI screenshot.','establishes':description,'qa':qa,'limitations':'Does not establish surrounding Workbench/plugin UI. No postprocessing, captions or compositing.'})
requested=[{'file':'01-workbench-hhat.png','status':'awaiting manual screenshot','scene':'01 HHAT unbound W6 and P8'}, {'file':'01b-workbench-hhat-receptor.png','status':'awaiting manual screenshot','scene':'01b HHAT receptor context'}, {'file':'02-workbench-kras-contacts.png','status':'awaiting manual screenshot','scene':'02 KRAS mutant Q70 R114 contacts'}, {'file':'03-workbench-sequences.png','status':'awaiting manual screenshot','scene':'Sequence card / side pane: peptides.afa; alignment mode accepted but later controls/row query unacknowledged'}, {'file':'04-literature-retrieval.png','status':'awaiting manual screenshot','scene':'Existing Poole Life Sciences Literature receipt; no fresh literature invocation this turn'}, {'file':'05-workbench-density.png','status':'unavailable','reason':'Native load_public_density failed before loading: active workspace-read roots not bound.'}]
out={'packageStatus':'incomplete: genuine Workbench UI screenshots pending','reviewedHandoffCommit':'1efd6e1','pluginsObserved':versions,'pluginsUsedThisTurn':['Molecular Structure Viewer','Biological Sequence & Alignment Viewer'],'notUsedThisTurn':['Life Sciences Literature (existing receipts only)','Rosalind Workbench parent UI (installed manifest only; not captured)'],'sources':sources,'images':images,'requestedUiCaptures':requested,'structureSessionId':'27b2aa7a-46bf-4964-98de-7c5d2c651c43','sequenceSessionId':'0b47940c-06ff-49f3-ae44-5bf5457d3b18','captureRestriction':'No UI screenshot tool is available through the native plugins. The handoff forbids retrying previously denied Computer Use or bypassing it. No retry or substitute UI was made.'}
(O/'index.json').write_text(json.dumps(out,indent=2)+'\n')
print(len(images),'original native PNGs indexed; zero genuine UI screenshots; manual capture remains required')
